#!/usr/bin/env bash
#  Bash script that will display information about subdomains.
if [ $# = 2 ]; then
subdomain="$2.$1"
ip=$(dig "$subdomain"  | awk ' NR==14 {print $5}')
record=$(dig "$subdomain" | awk 'NR==14 {print $4}')
echo "The subdomain $2 is a record $record and points to $ip"
else
subs=(www lb-01 web-01 web-02)
for item in "${subs[@]}"; do
	subdomain="$item.$1"
	ip=$(dig "$subdomain"  | awk ' NR==14 {print $5}')
	record=$(dig "$subdomain" | awk 'NR==14 {print $4}')
	echo "The subdomain $item is a $record record and points to $ip" 
done
fi
