#!/usr/bin/env bash
# Transfer a file to your server
sudo apt update 
sudo apt install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo bash -c 'cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location /redirect_me/ {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    # Additional server configuration...
}
}
EOF'
echo "Ceci n'est pas une page" > /var/www/html/404.html;
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
add_header="\n\tadd_header X-Served-By $(hostname);"
sed -i '/server {/ s/$/ '"$add_header"'/' /etc/nginx/sites-available/default
service nginx restart
