#!/usr/bin/env bash
# Nginx installation from listening on port 80
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/site-available/default /etc/ngix/site-enabled/default
sudo service  nginx restart
