#!/usr/bin/env bash
# Bash script that displays Best School 10 times
filename="school"
if [ -a "$filename" ]; then
	echo "school file exists"
	if [ -s "$filename" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
else
echo "school file does not exist"
fi
if [ -f "$filename" ]; then
	echo "school is regular file"
fi
