#!/usr/bin/env bash
# Run software as another user
bash -c 'cat << EOF >nginx.conf
worker_processes 1;
error_log stderr;
daemon off;
pid nginx.pid;
user nginx;

events {
  worker_connections  1024;
}

http {
  include             /etc/nginx/mime.types;
  default_type        application/octet-stream;

  sendfile on;

  keepalive_timeout   65;

  ssl_protocols TLSv1 TLSv1.1 TLSv1.2; 
  ssl_prefer_server_ciphers on;
  access_log access.log;
  server {
    listen            8080;
    server_name       localhost;

    location / {
      include /etc/nginx/uwsgi_params;
      uwsgi_pass localhost:8081;
    }
  }
}
EOF'
/usr/sbin/nginx -c nginx.conf -p "$PWD"
